### ISSUE TITLE
What is the ' in the ipa conversion output?

### ISSUE THREAD

**Issue by ZenMule** [andreihar/taibun#19]
This is not a bug report but just a question.
I noticed in the output of the IPA conversion from traditional Chinese,
some IPA symbols have a ' following them.
I tried to dig into the conversion script but couldn't figure out what it was.
Could you tell me what it represents?

**Comment by andreihar** [comment]
IPA conversion shouldn't leave any apostrophes unless they were given in the input. Certain International Phonetic Alphabet characters may not render correctly in the text editor, and might appear as apostrophes instead. Could you provide some examples of input text please?
